# Identidad del Sitio
title: Creamos
description: >-
  Plataforma de difusión política y análisis técnico. 
  Elevando el debate en Colombia mediante el rigor numérico y la visión popular.
email: johan.rvega34@gmail.com
baseurl: "/creamos"
url: "https://Jvega34.github.io"

# Logo Institucional (Ruta corregida)
# El manual exige máxima legibilidad y contraste [cite: 147]
logo: /assets/img/fondoClaro.png 

# Menú de Navegación (Limpio y en orden)
header_pages:
  - index.md
  - quienes-somos.md
  - analisis-numerico.md
  - vision-politica.md
  - datos-abiertos.md

# Títulos del Menú
titles:
  quienes-somos: "Quiénes Somos"
  analisis-numerico: "Análisis de Datos"
  vision-politica: "Visión Política"
