title: Creamos
description: >-
  Difusión de ideas políticas y análisis técnico. 
  Transformando datos en visión país desde el rigor numérico.
email: johan.rvega34@gmail.com
baseurl: "/creamos"
url: "https://Jvega34.github.io"
logo: assets/img/fondoClaro.png

# Menú de Navegación
header_pages:
  - index.md
  - quienes-somos.md
plugins:
  - jekyll-feed
  - jekyll-seo-tag
