steps:
  # UNIFICADO: Instalación y Compilación
  - name: 'ruby:3.2'
    entrypoint: bash
    args:
      - -c
      - |
        gem install bundler
        bundle install
        bundle exec jekyll build

  # DESPLIEGUE: Subir a Firebase
  - name: 'gcr.io/cloud-builders/firebase'
    args: ['deploy', '--only', 'hosting', '--project', '$PROJECT_ID']

options:
  logging: CLOUD_LOGGING_ONLY
